== Before You Hack

* The camera should be plugged into a 1,500 mA power source.  I don't think
it will charge from your laptop USB cable.  At least that was my experience.
If you have it plugged into your laptop, the WiFi, and thus the API access,
most likely won't work.  I have used it plugged into a wall charger with the
WiFi working.


* The THETA can connect to only one device at a time.  It can connect
to a phone or a computer, but not at the same time.  You can connect to
the THETA, but your team mate will not be able to connect to it at the same time.

* There are multiple THETAs at the hackathon with similar SSID access point
serial numbers. Make sure you connect to the right THETA.  The access point
is the serial number.

* By default, the WiFi password for the THETA S models at the hackathon
 is the last eight digits of the serial number.

* You can't change `captureMode` option to `_liveStreaming` with the API.
At least, no one has gotten it to work this way.  Live streaming
does work manually.  You can change capture mode to `image` or `_video` with
no problem.  The lack of `_liveStreaming` switching with the API is not obvious
from reading the API documentation.

* Live streaming is only in dual fish-eye mode.  It can't be switched to
output equirectangular video. If you need this, you will need to write your
own code to stitch it. (as of Sept 15, 2015)

* Live streaming won't work over WiFi.

* We don't have example code to de-fish the spherical image. Sorry, we ran
out of time.  :-(

* The WiFi signal is not strong.  Test the distance and signal strength before
you build your app.  I suggest you test a file download at different distances
so you can get a sense for how the distance affects transfer speeds.

* If you are using Google Maps APIs and want the end-user to use Streetview
to upload images, note that Streetview is a new app for
Android.  I think it needs Android KitKat or higher to work.
I have not tested it.
