== Next Steps

By using a library I was able to quickly prototype applications
with a number of interfaces.

. *Python command line*: this is the easiest to implement. It still
needs to handle errors.
. *Pygame library*: This is also quite easy to implement.  The most
time-consuming thing is making buttons.  It also has no error checking. `:-(`
Pygame is cross-platform on Windows, Mac, Linux, Android.  I have not
tested the code on Android and it will need minor modification.
I may have it by the time of the hackathon.
. *Kivy Python library*: This Python library runs on everything Pygame runs on
and runs on iOS.  It also has multi-touch and swipe support.
. *Hardware remote*: I built examples using https://flirc.tv/[FLIRC] to send IR
commands to a Raspberry Pi for a demo.  It's easy to do since the FLIRC
USB dongle simply translates keyboard commands.  I
used Pygame to capture keyboard presses.
Both Kivy and Pygame work with the Raspberry Pi. The remote example was
primarily a concept demo. Most people will probably use bluetooth.
. *External sensors*: By using a Raspberry Pi with external sensors, it is easy
to trigger the camera to take pictures with some input, such as
a motion detector, light, temperature, or position. I ran experiments
using the GPIO pins and physical buttons.
. *JavaScript*: I only have JavaScript working with Node.js now, not
within a browser. There are two NPM packages.

* https://www.npmjs.com/package/osc-client[OSC Client by turbobeast]
** https://github.com/BublTechnology/osc-client[GitHub repository of OCS Client]
* https://www.npmjs.com/package/osc-client-theta_s[OSC Client THETA S by horihiro]
** https://gitlab.com/horihiro/osc-client-theta_s#README[GitLab repository of Client OCS THETA S]
