== Next Steps

By using a library I was able to quickly prototype applications
with a number of interfaces.

. *Python command line*: this is the easiest to implement. It still
needs to handle errors.
. *Pygame library*: This is also quite easy to implement.  The most
time-consuming thing is making buttons.  It also has no error checking. `:-(`
Pygame is cross-platform on Windows, Mac, Linux, Android.  I have not
tested the code on Android and it will need minor modification.
I may have it by the time of the hackathon.
. *Kivy Python library*: This Python library runs on everything Pygame runs on
and runs on iOS.  It also has multi-touch and swipe support.
. *Hardware remote*: I was planning to use https://flirc.tv/[FLIRC] to send IR
commands to a Raspberry Pi for the demo.  It's easy to do since the FLIRC
USB dongle simply translates keyboard commands.  It would be easy to
use Pygame to capture keyboard presses.  Unfortunately, I ran out of time.
Both Kivy and Pygame work with the Raspberry Pi.  I have not tested this yet.
. *External sensors*: By using a Raspberry Pi with external sensors, it would
be easy to trigger the camera to take pictures with some input, such as
a motion detector, light, temperature, or position.
. *JavaScript*: I tried this for about 30 minutes using a `jQuery.ajax`
 and ran into a permissions error running it from a browser.  I did
 not try `node.js`, which may work.

WARNING: I believe that JavaScript will not work with a browser due to
camera-side (server-side) security settings. I think you may be able to to use
`node.js` to write JavaScript programs.  I have not tested it.  I
looked for a way to use jQuery with node.js.  It looked a bit involved,
so I just gave up and used Python.
