=== Python File Transfer

Here's an example of getting the file from the camera to a computer
or Android phone.  There's easier ways to get the file from the camera,
but this method works with the `requests` library.

There are two main parts. First grab the latest file URI from the
camera.  The second part is to transfer the file over and save it to
`output.jpg`

Set up the URL base.

  def request(url_request):
      url_base = "http://192.168.1.1/osc/"
      url = url_base + url_request
      return url

Grab the state information from the camera.

  def state():
      url = request("state")
      req = requests.post(url)
      response = req.json()
      return response

Assuming that you've just taken a picture, the camera will have the
attribute `_latestFileUri`.  If you haven't taken a picture in
the session, take a picture now for this test.

  def latestFileUri():
      state_data = state()["state"]
      latestFileUri = state_data["_latestFileUri"]
      return latestFileUri

Once you know the URI, you can grab the file and write it to
your local storage.

  def getImage(fileUri):
      url = request("commands/execute")
      body = json.dumps({"name": "camera.getImage",
           "parameters": {
              "fileUri": fileUri,
  #            "_type": "thumb"
              "_type": "image"
           }
           })
      with open('output.jpg', 'wb') as handle:
          response = requests.post(url, data=body, stream=True)
          for block in response.iter_content(1024):
              handle.write(block)


==== Other Command Line Python Tools

* https://github.com/theta360developers/python-download-rossgoderer[Python script downloader]
from Ulrich Rossgoderer. Community.
